### ISSUE TITLE
Comparison to chokidar

### ISSUE THREAD

**Issue by janwirth** [doowb/watch-cli#4]
I think watch-cli is easier to find, but chokidar seems more mature. Maybe a note in the repo description pointing towards chokidar makes sense.

**Comment by doowb** [comment]
Thanks for pointing this out. This repo doesn't use chokidar right now (it uses gaze), but since I use chokidar in many other places, I'll consider updating to chokidar and adding a link.

**Comment by janwirth** [comment]
There is chokidar-cli which does exactly what gaze does but a little less verbose!
